# 如需在系统变量中设置配置项，可使用GOTP_开头的变量名，如：GOTP_DB_PSQL_DBTYPE为db.psql.dbType

service:
  http: 
    host: 0.0.0.0 # 默认localhost
    port: # 默认9999

log:
  # 0-控制台输出 1-文件输出 2-文件和控制台输出
  adapter_type: 0
  # 文件最多保存多少天
  maxdays: 7
  # 日志级别 (panic fatal error warn info debug trace)
  level: debug # 默认info
  # 每个文件保存的最大行数
  maxlines: 10000

jwt:
  key: 1hj5b0sp9



db:
  psql:
    host: db # 默认localhost
    port: 5432 # 默认5432
    dbname: irrigate
    username: postgres
    password: postgres
    time_zone: Asia/Shanghai # 默认Asia/Shanghai

    idle_conns: 5 # 空闲连接池中的最大连接数，建议为open_conns的百分之5-20之间
    open_conns: 50 # 最大打开连接数,timescaledb默认为100,考虑到其他服务也会使用数据库，建议这里设置为50
    # SQL日志级别 (1-静音 2-错误 3-警告 4-信息)
    log_level: 4 # 默认1
    # 慢SQL阈值（毫秒）。慢SQL会在sqlloglevel大于等于3时输出。
    slow_threshold: 200 # 默认200毫秒

  redis:
    addr: 47.115.213.71:6379 # 默认localhost:6379
    db: 1 # 默认0
    password: "redis2022"



# mqtt服务：gmqtt、vernemq
mqtt_server: gmqtt

mqtt:
  broker: 127.0.0.1:1886 # 默认localhost:1883
  user: root # 默认root
  pass: root # 默认root
  channel_buffer_size: 10000 # 默认10000
  write_workers: 10 # 默认10
  #消息服务质量 0：消息最多传递一次，如果当时客户端不可用，则会丢失该消息。1：消息传递至少 1 次。2：消息仅传送一次。
  # 以下主题都为默认主题
  telemetry:
    publish_topic: devices/telemetry/{device_number}/{message_id}
    subscribe_topic: devices/telemetry
    pool_size: 100 # 默认100
    batch_size: 100 # 默认100 最大一次批量写入数据库的数据量
    qos: 0
  attributes:
    # 订阅属性：+位置是device_number
    subscribe_topic: devices/attributes/+
    # 接收属性响应：+/+位置是device_number/message_id
    publish_response_topic: devices/attributes/response/+/+
    # 设置属性：+位置是device_number
    publish_topic: devices/set/attributes/{device_number}/{message_id}
    # 设置属性响应：+位置是device_number
    subscribe_response_topic: devices/set/attributes/response/+
    # 获取属性：+位置是device_number
    publish_get_topic: devices/get/attributes/{device_number}
    qos: 1
  commands:
    publish_topic: devices/command/{device_number}/{message_id}
    subscribe_topic: devices/command/response/+
    qos: 1
  events:
    subscribe_topic: devices/events/+
    publish_topic: devices/event/response/{device_number}/{message_id}
    qos: 1
  ota:
    publish_topic: ota/device/infrom/{device_number}
    subscribe_topic: ota/device/progress
    qos: 1



mqtts:
  broker: 127.0.0.1:8883
  user: root
  pass: root
  caPath : ./conf/certificate/ca.crt
  crtPath: ./conf/certificate/client.crt
  keyPath : ./conf/certificate/client.key
