name: copy-image

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to Aliyuncs Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.IMAGE_USER }}
        password: ${{ secrets.IMAGE_PASS }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub
      run: |
         skopeo copy docker://docker.io/timescale/timescaledb:latest-pg14 docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/timescaledb:latest-pg14

    - name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub1
      run: |
         skopeo copy docker://docker.io/redis:latest docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/redis:latest

    - name: Use Skopeo Tools Sync Image to Aliyuncs Docker Hub2
      run: |
         skopeo copy docker://docker.io/library/golang:1.22-alpine3.20 docker://registry.cn-hangzhou.aliyuncs.com/thingspanel/golang:1.22-alpine3.20
