name: Automate Code Sync to Enterprise Repository

on:
  push:
    branches:
      - main  # 监听源仓库的 main 分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 防止自动使用 GitHub 的凭证
          fetch-depth: 0  # 获取所有提交历史

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "zjhong@users.noreply.github.com"
          git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.ACCESS_TOKEN }} | base64)"

      - name: Push changes
        run: |
          git push https://github.com/ThingsPanel/thingspanel-backend-enterprise.git main:thingspanel-backend-community --force
        env:
          PAT: ${{ secrets.ACCESS_TOKEN }}

