name: push-to-enterprise

on:
  push:
    branches:
      - main  # 当 main 分支有更新时自动触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 确保使用的是我们提供的凭证
          fetch-depth: 2  # 获取最近两次提交，足以处理当前推送

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<your-email>@users.noreply.github.com"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: thingspanel-backend-community
          repository: ThingsPanel/thingspanel-backend-enterprise
          force: false  # 根据需要选择是否使用 force 推送
          tags: true  # 如果需要推送标签，设为 true
