name: Publish Docker Images to GitHub

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker images to GitHub Container Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set lowercase owner name
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      
      - name: Pull and push TimescaleDB image
        run: |
          docker pull timescale/timescaledb:2.8.1-pg14
          docker tag timescale/timescaledb:2.8.1-pg14 ghcr.io/${{ env.OWNER_LC }}/timescaledb:2.8.1-pg14
          docker push ghcr.io/${{ env.OWNER_LC }}/timescaledb:2.8.1-pg14
      
      - name: Pull and push Redis image
        run: |
          docker pull redis:6.2.7
          docker tag redis:6.2.7 ghcr.io/${{ env.OWNER_LC }}/redis:6.2.7
          docker push ghcr.io/${{ env.OWNER_LC }}/redis:6.2.7